[build.processing.css]
bundle = true
minify = true
[build.processing.js]
bundle = true
minify = true
[[headers]]
for = "/*"
[headers.values]
Content-Encoding = "gzip"
Cache-Control = "public, max-age=31536000"
[[plugins]]
package = "@netlify/plugin-html-minifier"
